web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.example.com'
  ports:
    - '6080:80'
    - '6443:443'
    - '6022:22'
  volumes:
    - 'gitlab-config:/etc/gitlab'
    - 'gitlab-logs:/var/log/gitlab'
    - 'gitlab-ce:/var/opt/gitlab'
